---
- name: Setup MariaDB in Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Install software
      ansible.builtin.apt:
        name:
          - mariadb-server
          - qemu-guest-agent
          - libnss-myhostname
        update_cacke: True

    - name: Disable DNS lookup and enable own hostname lookup
      ansible.builtin.lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^hosts:'
        line: 'hosts:          files myhostname'

    - name: Make MariaDB listen to outside requests
      community.general.ini_file:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        option: bind-address
        section: mysqld
        value: 0.0.0.0
