---
- name: Setup MariaDB in Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Upgrade system packages
      apt:
        upgrade: safe
        update_cache: true

    - name: Install software
      apt:
        name:
        - mariadb-server
        - jq

    - name: Remove resolv.conf
      file:
        path: /etc/resolv.conf
        state: absent

    - name: Disable DNS lookup
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^hosts:'
        line: 'hosts:          files'
...