---
- name: Setup Apache and PHP in Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Upgrade system packages
      apt:
        upgrade: safe
        update_cache: true

    - name: Install software
      apt:
        name:
          - apache2
          - libapache2-mod-php
          - php
          - php-gd
          - php-mysqli
          - qemu-guest-agent
        autoclean: yes
        autoremove: yes

    - name: Sync buffers
      shell: 'sync; sleep 1; sync;'
