- name: Change Harbor admin password
  block:
    - name: Define retry variable
      ansible.builtin.set_fact:
        retry_with_new_password: False

    - name: Get admin id
      ansible.builtin.uri:
        url: https://harbor.local/api/v2.0/users/current
        url_username: admin
        url_password: '{{ harbor_admin_old_password }}'
        force_basic_auth: True
        method: GET
      register: admin_info

    - name: Update admin password
      when: harbor_admin_password != harbor_admin_old_password
      ansible.builtin.uri:
        url: 'https://harbor.local/api/v2.0/users/{{ admin_info.json.user_id }}/password'
        url_username: admin
        url_password: '{{ harbor_admin_old_password }}'
        force_basic_auth: True
        method: PUT
        body_format: json
        body:
          old_password: '{{ harbor_admin_old_password }}'
          new_password: '{{ harbor_admin_password }}'

  rescue:
    - name: Password was possibly already changed
      when: admin_info.status == 401 and harbor_admin_password != harbor_admin_old_password
      ansible.builtin.set_fact:
        retry_with_new_password: True

    - name: Run again with new password
      when: retry_with_new_password is defined and retry_with_new_password|bool
      ansible.builtin.include_tasks: change_admin_password.yml
      vars:
        harbor_admin_old_password: '{{ harbor_admin_password }}'
