---
- name: Create Kubernetes cluster
  hosts:
    - k8s
  become: False
  gather_facts: False
  roles:
    - name: k8s

- name: Install OVN Kubernetes
  hosts:
    - node0
  become: False
  gather_facts: True
  roles:
    - name: geerlingguy.pip
      become: True
      pip_install_packages:
        - name: jinjanator

    - name: ovn-kubernetes
