---
- name: Prerrequisites
  hosts: k8s
  become: False
  vars:
    pod_network_cidr: 10.80.0.0/12
    tigera_version: v3.27.0
  tasks:
    - name: Init cluster
      run_once: True
      block:
        - name: Init cluster
          become: True
          ansible.builtin.command:
            argv:
              - /usr/bin/kubeadm
              - init
              - '--pod-network-cidr={{ pod_network_cidr }}'
            creates: /etc/kubernetes/kubelet.conf
          register: kubeadm_init

        - name: Create kubectl directory
          ansible.builtin.file:
            path: /home/ubuntu/.kube
            state: directory
            mode: '0700'

        - name: Setup kubectl
          become: True
          ansible.builtin.copy:
            remote_src: True
            src: /etc/kubernetes/admin.conf
            dest: /home/ubuntu/.kube/config
            mode: '0600'
            owner: ubuntu
            group: ubuntu

        - name: Install python3-kubernetes
          become: True
          ansible.builtin.apt:
            name: python3-kubernetes
            state: present

        - name: Download Tigera operator YAML
          ansible.builtin.get_url:
            url: 'https://raw.githubusercontent.com/projectcalico/calico/{{ tigera_version }}/manifests/tigera-operator.yaml'
            dest: /tmp/tigera-operator.yaml

        - name: Install Tigera operator
          kubernetes.core.k8s:
            state: present
            src: /tmp/tigera-operator.yaml

        - name: Download Calico Custom Resources
          ansible.builtin.get_url:
            url: 'https://raw.githubusercontent.com/projectcalico/calico/{{ tigera_version }}/manifests/custom-resources.yaml'
            dest: /tmp/custom-resources.yaml

        - name: Set pod CIDR in Calico Custom Resources
          ansible.builtin.lineinfile:
            path: /tmp/custom-resources.yaml
            line: '      cidr: {{ pod_network_cidr }}'
            regexp: 'cidr: '
            state: present

        - name: Install Calico
          kubernetes.core.k8s:
            state: present
            src: /tmp/custom-resources.yaml

    - name: Join other nodes
      become: True
      ansible.builtin.shell:
        cmd: |
          {{ kubeadm_init.stdout_lines[-2] }}
          {{ kubeadm_init.stdout_lines[-1] }}
        creates: /etc/kubernetes/kubelet.conf
