---
- name: Install Harbor
  hosts:
    - harbor
  become: False
  gather_facts: True
  gather_subset:
    - '!all'
    - interfaces
  roles:
    - name: harbor

- name: Create Kubernetes cluster
  hosts:
    - k8s
  become: False
  gather_facts: False
  roles:
    - name: k8s
      pod_network_cidr: 172.20.0.0/16

- name: OpenStack integration
  hosts:
    - node0
  become: False
  gather_facts: False
  pre_tasks:
    - name: Install Helm
      ansible.builtin.include_role:
        name: geerlingguy.helm
        apply:
          become: True
      vars:
        helm_version: v3.16.1
    - name: Install Git
      become: True
      ansible.builtin.apt:
        name:
          - git
        state: present
    - name: Install Helm diff
      become: False
      kubernetes.core.helm_plugin:
        plugin_path: https://github.com/databus23/helm-diff
        state: present
  roles:
    - name: k8s_openstack
