---
- name: Install Harbor
  hosts:
    - harbor
  become: False
  gather_facts: True
  gather_subset:
    - '!all'
    - interfaces
  roles:
    - name: harbor

- name: Create Kubernetes cluster
  hosts:
    - k8s
  become: False
  gather_facts: False
  roles:
    - name: k8s
      pod_network_cidr: 172.20.0.0/16

- name: OpenStack integration
  hosts:
    - node0
  become: False
  gather_facts: False
  roles:
    - name: geerlingguy.helm
      become: True
      helm_version: v3.16.1
    - name: k8s_openstack
