---
- name: Fetch Cinder CSI Plugin manifests
  ansible.builtin.get_url:
    url: '{{ manifests_base_url }}/cinder-csi-plugin/{{ item }}'
    dest: '{{ manifest_dir }}/{{ item }}'
    mode: '0600'
  loop: '{{ cinder_csi_plugin_manifests }}'

- name: Apply Cinder CSI Plugin manifests
  kubernetes.core.k8s:
    src: '{{ manifest_dir }}/{{ item }}'
  loop: '{{ cinder_csi_plugin_manifests }}'

- name: Apply Storage Class
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: csi-sc-cinder
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: cinder.csi.openstack.org
      parameters:
        availability: nova
      allowVolumeExpansion: true
      volumeBindingMode: Immediate
