---
- name: CSI Driver NFS Helm repository
  kubernetes.core.helm_repository:
    name: csi-driver-nfs
    repo_url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts

- name: CSI Driver NFS Chart
  kubernetes.core.helm:
    name: csi-driver-nfs
    chart_ref: csi-driver-nfs/csi-driver-nfs
    release_namespace: kube-system

- name: Cloud Provider Openstack Helm repository
  kubernetes.core.helm_repository:
    name: cloud-provider-openstack
    repo_url: https://kubernetes.github.io/cloud-provider-openstack

- name: Manila CSI Plugin Chart
  kubernetes.core.helm:
    name: manila-csi
    chart_ref: cloud-provider-openstack/openstack-manila-csi
    release_namespace: kube-system

- name: Manila Configuration Secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: csi-manila-secrets
        namespace: kube-system
      stringData:
        os-authURL: '{{ openstack_auth_url }}'
        os-region: RegionOne
        os-applicationCredentialID: '{{ credential_id }}'
        os-applicationCredentialSecret: '{{ credential_secret }}'

- name: Manila CSI StorageClass
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: csi-manila-nfs
      provisioner: nfs.manila.csi.openstack.org
      allowVolumeExpansion: true
      parameters:
        type: default
        shareNetworkID: '{{ share_network_id }}'
        csi.storage.k8s.io/provisioner-secret-name: csi-manila-secrets
        csi.storage.k8s.io/provisioner-secret-namespace: kube-system
        csi.storage.k8s.io/controller-expand-secret-name: csi-manila-secrets
        csi.storage.k8s.io/controller-expand-secret-namespace: kube-system
        csi.storage.k8s.io/node-stage-secret-name: csi-manila-secrets
        csi.storage.k8s.io/node-stage-secret-namespace: kube-system
        csi.storage.k8s.io/node-publish-secret-name: csi-manila-secrets
        csi.storage.k8s.io/node-publish-secret-namespace: kube-system
